# from https://github.com/big-data-europe/docker-kafka

FROM bde2020/kafka

MAINTAINER Karl-Heinz Sylla <karl-heinz.sylla@iais.fraunhofer.de>

COPY ./kafka-producer.sh /

CMD [ "./kafka-producer.sh" ]
